In [21]:
import pandas as pd

In [24]:
gdp = pd.read_csv("gdp.csv")
inflation = pd.read_csv("inflation.csv")
exchange= pd.read_csv("exchange_rate.csv")
ip= pd.read_csv("industrial_production.csv")
forex = pd.read_csv("forex_reserves.csv")
exports = pd.read_csv("exports.csv")

In [30]:
exports = exports.drop(columns=["Unnamed: 0"])

KeyError: "['Unnamed: 0'] not found in axis"

In [29]:
forex = forex.drop(columns=["Unnamed: 0"])

In [31]:
master = gdp.merge(inflation, on="Year", how="outer")
master = master.merge(exchange, on="Year", how="outer")
master = master.merge(ip, on="Year", how="outer")
master = master.merge(forex, on="Year", how="outer")
master = master.merge(exports, on="Year", how="outer")
master

,Unnamed: 0,Year,GDP,Inflation,Exchange rate,Industrial_Production,Forex_Reserves,Exports
0,NaN,1996.0,NaN,NaN,NaN,NaN,NaN,1170.504
1,1.0,1997.0,608093.5,NaN,36.32046,NaN,0.659740,1269.848
2,2.0,1998.0,644683.9,NaN,41.23745,2.200000e+11,0.699389,1378.671
3,3.0,1999.0,689324.5,NaN,43.05785,2.330000e+11,0.743921,1536.025
4,4.0,2000.0,728354.6,NaN,44.94066,2.470000e+11,0.777293,1909.391
5,5.0,2001.0,756637.5,NaN,47.17988,2.540000e+11,0.955777,2045.921
6,6.0,2002.0,791449.3,5.206416,48.59392,2.670000e+11,1.259105,2455.365
7,7.0,2003.0,845814.2,4.339540,46.57471,2.840000e+11,1.422541,2748.953
8,8.0,2004.0,911152.4,3.853640,45.30096,3.150000e+11,1.314929,3475.747
9,9.0,2005.0,993306.1,3.739476,44.09727,3.440000e+11,0.961877,4391.150
10,10.0,2006.0,1086039.0,6.061532,45.28342,3.860000e+11,0.996001,5520.650
11,11.0,2007.0,1195209.0,5.992872,41.35377,4.460000e+11,1.202799,6197.286
12,12.0,2008.0,1269547.0,8.571287,43.52441,4.810000e+11,0.797138,8409.359
13,13.0,2009.0,1334473.0,9.723108,48.42569,4.820000e+11,1.101097,7985.091
14,14.0,2010.0,1480055.0,10.359860,45.73159,5.280000e+11,0.847258,10284.620
15,15.0,2011.0,1595095.0,8.309827,46.66909,5.540000e+11,0.638673,14104.240
16,16.0,2012.0,1687476.0,9.378961,53.41422,5.580000e+11,0.603500,15832.510
17,17.0,2013.0,1791203.0,10.412860,58.55305,5.680000e+11,0.632002,18439.660
18,18.0,2014.0,1916714.0,6.637531,61.02941,5.940000e+11,0.693634,19670.800
19,19.0,2015.0,2060492.0,4.873544,64.13791,6.090000e+11,0.890946,17160.620
20,20.0,2016.0,2246004.0,4.974869,67.18516,6.400000e+11,0.993771,17758.970
21,21.0,2017.0,2383280.0,3.327170,65.11012,6.630000e+11,0.910085,19459.780
22,22.0,2018.0,2556453.0,3.920453,68.40717,6.970000e+11,0.768621,22228.360
23,23.0,2019.0,2673906.0,3.746322,70.43223,7.020000e+11,0.945696,22828.720
24,24.0,2020.0,2510261.0,6.614196,74.12084,6.240000e+11,1.574827,20471.590
25,25.0,2021.0,2749380.0,5.145997,73.90728,7.050000e+11,1.107483,29332.470
26,26.0,2022.0,2942618.0,6.677845,78.59254,7.380000e+11,0.780657,35657.540
27,27.0,2023.0,3150165.0,5.654064,82.58736,7.800000e+11,0.925055,35714.600
28,28.0,2024.0,3377677.0,4.978250,83.66917,8.140000e+11,0.885586,37067.780
29,29.0,2025.0,3630711.0,2.187101,87.16593,8.450000e+11,NaN,NaN
30,30.0,2026.0,NaN,2.743692,92.73196,NaN,NaN,NaN

In [32]:
master = master.drop(columns=["Unnamed: 0"])

In [34]:
master.head(20)

,Year,GDP,Inflation,Exchange rate,Industrial_Production,Forex_Reserves,Exports
0,1996.0,NaN,NaN,NaN,NaN,NaN,1170.504
1,1997.0,608093.5,NaN,36.32046,NaN,0.659740,1269.848
2,1998.0,644683.9,NaN,41.23745,2.200000e+11,0.699389,1378.671
3,1999.0,689324.5,NaN,43.05785,2.330000e+11,0.743921,1536.025
4,2000.0,728354.6,NaN,44.94066,2.470000e+11,0.777293,1909.391
5,2001.0,756637.5,NaN,47.17988,2.540000e+11,0.955777,2045.921
6,2002.0,791449.3,5.206416,48.59392,2.670000e+11,1.259105,2455.365
7,2003.0,845814.2,4.339540,46.57471,2.840000e+11,1.422541,2748.953
8,2004.0,911152.4,3.853640,45.30096,3.150000e+11,1.314929,3475.747
9,2005.0,993306.1,3.739476,44.09727,3.440000e+11,0.961877,4391.150
10,2006.0,1086039.0,6.061532,45.28342,3.860000e+11,0.996001,5520.650
11,2007.0,1195209.0,5.992872,41.35377,4.460000e+11,1.202799,6197.286
12,2008.0,1269547.0,8.571287,43.52441,4.810000e+11,0.797138,8409.359
13,2009.0,1334473.0,9.723108,48.42569,4.820000e+11,1.101097,7985.091
14,2010.0,1480055.0,10.359860,45.73159,5.280000e+11,0.847258,10284.620
15,2011.0,1595095.0,8.309827,46.66909,5.540000e+11,0.638673,14104.240
16,2012.0,1687476.0,9.378961,53.41422,5.580000e+11,0.603500,15832.510
17,2013.0,1791203.0,10.412860,58.55305,5.680000e+11,0.632002,18439.660
18,2014.0,1916714.0,6.637531,61.02941,5.940000e+11,0.693634,19670.800
19,2015.0,2060492.0,4.873544,64.13791,6.090000e+11,0.890946,17160.620

In [37]:
master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   31 non-null     int64
 1   GDP                    29 non-null     float64
 2   Inflation              25 non-null     float64
 3   Exchange rate          30 non-null     float64
 4   Industrial_Production  28 non-null     float64
 5   Forex_Reserves         28 non-null     float64
 6   Exports                29 non-null     float64
dtypes: float64(6), int64(1)
memory usage: 1.8 KB

In [36]:
master["Year"]= master["Year"].astype(int)

In [38]:
master.isnull().sum()master.isnull().sum()

Year                     0
GDP                      2
Inflation                6
Exchange rate            1
Industrial_Production    3
Forex_Reserves           3
Exports                  2
dtype: int64

In [39]:
master.to_csv("Indian_Economy_Master.csv", index=False)